/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#382f25",
        "surface-container-highest": "#3c3329",
        "secondary-fixed-dim": "#bcc7de",
        "background": "#19120a",
        "surface": "#19120a",
        "inverse-surface": "#f0e0d1",
        "surface-bright": "#41382e",
        "primary": "#ffc174",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#d8e3fb",
        "inverse-primary": "#855300",
        "surface-dim": "#19120a",
        "primary-fixed": "#ffddb8",
        "on-tertiary-container": "#004966",
        "on-background": "#f0e0d1",
        "on-primary-fixed-variant": "#653e00",
        "surface-container-high": "#31281f",
        "on-surface": "#f0e0d1",
        "error": "#ffb4ab",
        "on-tertiary": "#00344a",
        "on-secondary": "#263143",
        "surface-tint": "#ffb95f",
        "on-secondary-container": "#aeb9d0",
        "primary-fixed-dim": "#ffb95f",
        "on-surface-variant": "#d8c3ad",
        "on-error": "#690005",
        "tertiary-fixed": "#c5e7ff",
        "on-tertiary-fixed": "#001e2d",
        "on-primary": "#472a00",
        "outline": "#a08e7a",
        "surface-container-lowest": "#140d06",
        "primary-container": "#f59e0b",
        "error-container": "#93000a",
        "secondary-container": "#3e495d",
        "secondary": "#bcc7de",
        "on-primary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#004c6a",
        "surface-container-low": "#221a12",
        "tertiary-fixed-dim": "#7fd0ff",
        "on-secondary-fixed": "#111c2d",
        "surface-variant": "#3c3329",
        "on-primary-container": "#613b00",
        "tertiary": "#8fd5ff",
        "surface-container": "#261e15",
        "outline-variant": "#534434",
        "tertiary-container": "#1abdff",
        "on-secondary-fixed-variant": "#3c475a"
      },
    },
  },
  plugins: [],
};
